vich_uploader:
  db_driver: orm

  mappings:
    examples:
      uri_prefix: /uploads/examples
      upload_destination: "%kernel.project_dir%/public/uploads/examples"
      namer: vich_uploader.namer_uniqid
