easy_admin:
  design:
    menu:
      - label: "Site"
        icon: "newspaper-o"
        children:
          - { entity: "MachineCategory", icon: newspaper-o, label: "Categories de machines" }
          - { entity: "Machines", icon: newspaper-o, label: "Machines" }

      - label: "User"
        icon: "user-circle"
        children:
          - { entity: "User", icon: user-circle, label: "User" }
