easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: 'Utilisateurs'
      # Notre controller spécifique
      controller: App\Controller\Admin\User\UserAdminController
      list:
          fields: 
          - { property: "id" }
          - { property: "email", label: 'E-mail' }
      form:
        fields:
          - { property: "email", label: 'E-mail' }
          - property: "plainPassword"
            type: "password"
            type_options: { required: false }
            label: "Mot de passe"
          - property: "roles"
            type: "choice"
            label: 'Rôle'
            type_options:
              mapped: true
              expanded: true
              multiple: true
              choices: { "User": "ROLE_USER", "Administrateur": "ROLE_ADMIN" }